spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://sql.freedb.tech:3306/freedb_cluster_delta
    username: freedb_delta
    password: Mv6%$8D*VmkVsht
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8083
